version: "2"
services:
  microservice1:
    image: microservice1
    container_name: microservice1
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    mem_limit: 1024M
    mem_reservation: 512M
    ports:
    - 8080:8080
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Network_app

  microservice2:
    container_name: microservice2
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    image: microservice2
    restart: on-failure
    tty: true
    mem_limit: 1024M
    mem_reservation: 512M
    ports:
      - 9090:9090
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Network_app

  grafana:
    ports:
     - 3000:3000
    image: grafana/grafana
    container_name: grafana
    networks:
      - Network_app

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /Users/ritgirdh/Desktop/codebase/study/microservices-prometheus-demo/prometheus/conf/:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    networks:
      - Network_app

networks:
  Network_app: